controller_list:
  - name: fake_arm2_controller
    type: $(arg fake_execution_type)
    joints:
      - two_joint_s
      - two_joint_l
      - two_joint_e
      - two_joint_u
      - two_joint_r
      - two_joint_b
      - two_joint_t
      - left_gripper_finger_left_joint
  - name: fake_arm1_controller
    type: $(arg fake_execution_type)
    joints:
      - one_joint_s
      - one_joint_l
      - one_joint_e
      - one_joint_u
      - one_joint_r
      - one_joint_b
      - one_joint_t
      - right_gripper_finger_left_joint
  - name: fake_dual_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - one_joint_s
      - one_joint_l
      - one_joint_e
      - one_joint_u
      - one_joint_r
      - one_joint_b
      - one_joint_t
      - right_gripper_finger_left_joint
      - two_joint_s
      - two_joint_l
      - two_joint_e
      - two_joint_u
      - two_joint_r
      - two_joint_b
      - two_joint_t
      - left_gripper_finger_left_joint
  - name: fake_gripper1_controller
    type: $(arg fake_execution_type)
    joints:
      - right_gripper_finger_left_joint
  - name: fake_gripper2_controller
    type: $(arg fake_execution_type)
    joints:
      - left_gripper_finger_left_joint
initial:  # Define initial robot poses per group
  - group: dual_arm
    pose: home